### PR TITLE
Added vehicle diagnostics for additional sensors

### PR DESCRIPTION
**Pull request by aerrow5**
Creating PR is not my daily business, so hope it works well.
As created in #75

### CODE REVIEW

**Comment by Dielee** [comment]
Thanks for the PR!
Why are all the new sensors relevant for long term statistics?

**Comment by aerrow5** [comment]
You're right on this, there is not need to activate long term statistics.

**Comment by Dielee** [comment]
Would you please change this, I will merge later!

**Comment by aerrow5** [comment]
Updated by removing the state_class.

**Pull request merged**
