### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by dpiekacz**

### CODE REVIEW

**Comment by dpiekacz** [comment]
Sorry, didn't notice I created that PR to merge with your repo instead of my fork.

**Comment by Dielee** [comment]
What's the purpose of your "code_review" branch ?

**Comment by dpiekacz** [comment]
Sorry, it was created by mistake.

**Comment by dpiekacz** [comment]
btw, I use your project and had an issue the docker container stopping. It was related with the car not supporting one of capabilities and the query was failing what stopped the process. I started correcting it on my own and adding pytest based tests.

**Comment by dpiekacz** [comment]
Thank you for creating this project. Great work.

**Comment by Dielee** [comment]
Thanks for the pizza ;)

**Pull request closed without merging**
